apiVersion: v1
kind: Service
metadata:
  name: generatedate-service
  labels:
    app: generatedate
spec:
  type: LoadBalancer
  selector:
    app: generatedate
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
